# `Automatic Image downloading in folder`

In [11]:
def Image_search(search_name):
    import requests
    import os
    url = "https://real-time-image-search.p.rapidapi.com/search"

    querystring = {"query":search_name,"limit":"10","size":"any","color":"any","type":"any","time":"any","usage_rights":"any","file_type":"any","aspect_ratio":"any","safe_search":"off","region":"us"}
    
    headers = {
    	"x-rapidapi-key": "7cbfcfe4ecmshc8885e0effbd816p145679jsnc7988faadadc",
    	"x-rapidapi-host": "real-time-image-search.p.rapidapi.com",
    	"Content-Type": "application/json"
    }
    
    response = requests.get(url, headers=headers, params=querystring)
    if response.status_code == 200:
        data = response.json()
        url_list =[]
        for i in range(0,len(data["data"])):
            url_list.append(data['data'][i]['thumbnail_url'])
    
        current_path = os.getcwd()
        os.mkdir(search_name)
        os.chdir(search_name)
        print(f"Enter into {os.getcwd()}")
    
        c=1
        for url in url_list:
            resp = requests.get(url)
            img =resp.content
            with open(f"img{c}.jpeg","wb") as file:
                file.write(img)
                c+=1
        else:
            print("Image downloaded...")
            os.chdir(current_path)
            print(f"finally in {os.getcwd()}")
        
    
    else:
        print(response.reason)

In [12]:
Image_search("cars")

Enter into C:\Users\Manish Gupta\Downloads\GRRAS\Exceptional Handling\cars
Image downloaded...
finally in C:\Users\Manish Gupta\Downloads\GRRAS\Exceptional Handling

# `Take data from rapid api and fetch data and show in pandas`

In [18]:
import requests

url = "https://jsearch.p.rapidapi.com/search"

querystring = {"query":"developer jobs in chicago","page":"1","num_pages":"2","country":"us","date_posted":"all"}

headers = {
	"x-rapidapi-key": "7cbfcfe4ecmshc8885e0effbd816p145679jsnc7988faadadc",
	"x-rapidapi-host": "jsearch.p.rapidapi.com",
	"Content-Type": "application/json"
}

response = requests.get(url, headers=headers, params=querystring)

data = response.json()

# `collect details`

In [19]:
title = []
emp_name =[]
job_publish = []
job_employment_type = []
job_apply_link = []
job_posted_at =[]
job_city = []
job_country = []
for i in range(len(data['data'])):
    title.append(data['data'][i]['job_title'])
    emp_name.append(data['data'][i]['employer_name'])
    job_publish.append(data['data'][i]['job_publisher'])
    job_employment_type.append(data['data'][i]['job_employment_type'])
    job_apply_link.append(data['data'][i]['job_apply_link'])
    job_posted_at.append(data['data'][i] ['job_posted_at'])
    job_city.append(data['data'][i] ['job_city'])
    job_country.append(data['data'][i]['job_country'])
else:
    print("Done")

Done

# `now show in pandas`

In [20]:
import pandas as pd 
data = pd.DataFrame({
    "job title" : title,
    "Employer_name": emp_name,
    "job_pulisher" :job_publish,
    "job_employment_type": job_employment_type,
    "job_apply_link":job_apply_link,
    "job_posted_at":job_posted_at,
    "job city": job_city,
    "job country": job_country
})
data

,job title,Employer_name,job_pulisher,job_employment_type,job_apply_link,job_posted_at,job city,job country
0,React Native Developer - 100% Remote position,HYR Global Source Inc,LinkedIn,Full-time,https://www.linkedin.com/jobs/view/react-nativ...,12 hours ago,Chicago,US
1,Developer,SAP,SAP Careers,Full-time,https://jobs.sap.com/job/Chicago-Developer-IL-...,3 days ago,Chicago,US
2,Full-Stack Developer (React / .NET),recruit22 LLC,Indeed,Full-time,https://www.indeed.com/viewjob?jk=8e1cab62e15e...,10 hours ago,Chicago,US
3,Fullstack Developer/Monitoring role,MAXQ Infotech,LinkedIn,Full-time,https://www.linkedin.com/jobs/view/fullstack-d...,17 hours ago,Chicago,US
4,"SharePoint/PowerPlatform developer_Chicago, IL...",AceStack,LinkedIn,Full-time,https://www.linkedin.com/jobs/view/sharepoint-...,16 hours ago,Chicago,US
5,Principal Developer - IT,United Airlines,United Airlines Jobs,Full-time,https://careers.united.com/us/en/job/WHQ000261...,1 day ago,Chicago,US
6,"Software Engineer - Full Stack in Chicago, Ill...",US Bank,ZipRecruiter,Full-time,https://www.ziprecruiter.com/c/U.S.-Bank/Job/S...,3 days ago,Chicago,US
7,Full Stack Developer,USG Corporation,USG Corporation,Full-time,https://careers.usg.com/jobs/7157761-full-stac...,6 days ago,Chicago,US
8,Senior Developer - .Net/AWS,United Airlines,United Airlines Jobs,Full-time,https://careers.united.com/us/en/job/WHQ000258...,1 day ago,Chicago,US
9,"Software Engineer, Test",Cboe Global Markets,Cboe Global Markets Jobs,Full-time,https://careers.cboe.com/us/en/job/R-4331/Soft...,1 month ago,Chicago,US
10,"Full-Stack Quant Developer | Chicago, IL- Prop...",Oxford Knight,EFinancialCareers,Full-time,https://www.efinancialcareers.com/jobs-USA-IL-...,7 days ago,Chicago,US
11,Mid-Level Software Engineer / C# and C++,Motion Recruitment,LinkedIn,Full-time,https://www.linkedin.com/jobs/view/mid-level-s...,1 day ago,Chicago,US
12,"Lead Software Engineer (Java, Python) 🏆",CME Group,DevITjobs,Full-time,https://devitjobs.com/jobs/CME-Group-Lead-Soft...,3 days ago,Chicago,US
13,Software Engineer (Corporate Functions) - Chic...,Lenovo,Indeed,Full-time,https://www.indeed.com/viewjob?jk=7c3c10bae813...,None,Chicago,US
14,"Principal Software Engineer- $160,000-$210,000...",Saragossa,LinkedIn,Full-time,https://www.linkedin.com/jobs/view/principal-s...,3 days ago,Chicago,US
15,Full Stack Developers,Seven Seven Software,ZipRecruiter,Full-time,https://www.ziprecruiter.com/c/Seven-Seven-Sof...,None,Chicago,US
16,Full Stack Software Developer,Sarnova,Monster,Full-time,https://www.monster.com/job-openings/full-stac...,13 days ago,Chicago,US
17,"Sr Lead Software Engineer - Java, Kafka, AI, S...",JPMorganChase,Indeed,Full-time,https://www.indeed.com/viewjob?jk=a83674db9059...,None,Chicago,US
18,Principal Back-end Software Engineer - Real-Ti...,Cboe Global Markets,Cboe Global Markets Jobs,Full-time,https://careers.cboe.com/us/en/job/R-3747/Prin...,5 days ago,Chicago,US

# `now convert in csv file`

In [22]:
data.to_csv("linked.csv")

In [23]:
df = pd.read_csv("linked.csv")
df

,Unnamed: 0,job title,Employer_name,job_pulisher,job_employment_type,job_apply_link,job_posted_at,job city,job country
0,0,React Native Developer - 100% Remote position,HYR Global Source Inc,LinkedIn,Full-time,https://www.linkedin.com/jobs/view/react-nativ...,12 hours ago,Chicago,US
1,1,Developer,SAP,SAP Careers,Full-time,https://jobs.sap.com/job/Chicago-Developer-IL-...,3 days ago,Chicago,US
2,2,Full-Stack Developer (React / .NET),recruit22 LLC,Indeed,Full-time,https://www.indeed.com/viewjob?jk=8e1cab62e15e...,10 hours ago,Chicago,US
3,3,Fullstack Developer/Monitoring role,MAXQ Infotech,LinkedIn,Full-time,https://www.linkedin.com/jobs/view/fullstack-d...,17 hours ago,Chicago,US
4,4,"SharePoint/PowerPlatform developer_Chicago, IL...",AceStack,LinkedIn,Full-time,https://www.linkedin.com/jobs/view/sharepoint-...,16 hours ago,Chicago,US
5,5,Principal Developer - IT,United Airlines,United Airlines Jobs,Full-time,https://careers.united.com/us/en/job/WHQ000261...,1 day ago,Chicago,US
6,6,"Software Engineer - Full Stack in Chicago, Ill...",US Bank,ZipRecruiter,Full-time,https://www.ziprecruiter.com/c/U.S.-Bank/Job/S...,3 days ago,Chicago,US
7,7,Full Stack Developer,USG Corporation,USG Corporation,Full-time,https://careers.usg.com/jobs/7157761-full-stac...,6 days ago,Chicago,US
8,8,Senior Developer - .Net/AWS,United Airlines,United Airlines Jobs,Full-time,https://careers.united.com/us/en/job/WHQ000258...,1 day ago,Chicago,US
9,9,"Software Engineer, Test",Cboe Global Markets,Cboe Global Markets Jobs,Full-time,https://careers.cboe.com/us/en/job/R-4331/Soft...,1 month ago,Chicago,US
10,10,"Full-Stack Quant Developer | Chicago, IL- Prop...",Oxford Knight,EFinancialCareers,Full-time,https://www.efinancialcareers.com/jobs-USA-IL-...,7 days ago,Chicago,US
11,11,Mid-Level Software Engineer / C# and C++,Motion Recruitment,LinkedIn,Full-time,https://www.linkedin.com/jobs/view/mid-level-s...,1 day ago,Chicago,US
12,12,"Lead Software Engineer (Java, Python) 🏆",CME Group,DevITjobs,Full-time,https://devitjobs.com/jobs/CME-Group-Lead-Soft...,3 days ago,Chicago,US
13,13,Software Engineer (Corporate Functions) - Chic...,Lenovo,Indeed,Full-time,https://www.indeed.com/viewjob?jk=7c3c10bae813...,NaN,Chicago,US
14,14,"Principal Software Engineer- $160,000-$210,000...",Saragossa,LinkedIn,Full-time,https://www.linkedin.com/jobs/view/principal-s...,3 days ago,Chicago,US
15,15,Full Stack Developers,Seven Seven Software,ZipRecruiter,Full-time,https://www.ziprecruiter.com/c/Seven-Seven-Sof...,NaN,Chicago,US
16,16,Full Stack Software Developer,Sarnova,Monster,Full-time,https://www.monster.com/job-openings/full-stac...,13 days ago,Chicago,US
17,17,"Sr Lead Software Engineer - Java, Kafka, AI, S...",JPMorganChase,Indeed,Full-time,https://www.indeed.com/viewjob?jk=a83674db9059...,NaN,Chicago,US
18,18,Principal Back-end Software Engineer - Real-Ti...,Cboe Global Markets,Cboe Global Markets Jobs,Full-time,https://careers.cboe.com/us/en/job/R-3747/Prin...,5 days ago,Chicago,US